name: CI/CD Pipeline


on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '*/5 * * * *'
  healthcheck:
    name: Health Check (Every 5 min)
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Call /api/health endpoint
        run: |
          curl -f https://collectibles-store.onrender.com/api/health || echo "Health check failed"

env:
  JAVA_VERSION: '11'
  MAVEN_VERSION: '3.8.6'
  POSTGRES_VERSION: '15'

name: Health Check Only

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  healthcheck:
    name: Health Check (Every 5 min)
    runs-on: ubuntu-latest
    steps:
      - name: Call /api/health endpoint
        run: |
          curl -f https://collectibles-store.onrender.com/api/health || echo "Health check failed"
          --health-interval 10s

          --health-timeout 5s

          --health-retries 5

        ports:
