name: Health Check Only

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  healthcheck:
    name: Health Check (Every 5 min)
    runs-on: ubuntu-latest
    steps:
      - name: Call /api/health endpoint
        run: |
          curl -f https://collectibles-store.onrender.com/api/health || echo "Health check failed"
